server:
    port: 8080
    display-name: bs-dreamport-user
    context-path: /bs-dreamport-user

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.int(10000,19999)}
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
    datasource:
      druid:
        #JDBC配置
        url: jdbc:mysql://127.0.0.1:3306/dreamport
        username: root
        password: 123456
        driverClassName: com.mysql.jdbc.Driver
        #连接池配置
        initialSize: 1
        maxActive: 20
        minIdle: 1
        maxWait: 60000
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        validationQuery: select 'x'
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        filters: stat
        #监控配置
        # WebStatFilter配置
        web-stat-filter:
          enabled: true
          url-pattern: /*
          exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
        # StatViewServlet配置
        stat-view-servlet:
          enabled: true
          url-pattern: /druid/*
          reset-enable: true
          login-username: admin
          login-password: admin
        aop-patterns: com.dreamport.service.service.*


dreamport:
  druid:
    login:
      username: admin
      password: admin

#mybatis:
#  mapperLocations: classpath:mapper/*.xml
#  typeAliasesPackage: com.dreamport.domain
#  configuration:
#    mapUnderscoreToCamelCase: true
#    defaultStatementTimeout: 5000
#    lazyLoadingEnabled: false


mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.dreamport.domain
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #SQL逻辑删除注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

# Log 配置 级别大写 TRACE|DEBUG|INFO|WARN|ERROR
logging:
  level:
    #root: INFO
    com.dreamport: DEBUG
    com.ibatis: DEBUG
    java.sql: DEBUG

# actuator 安全性配置
security:
  basic:
    enabled:  true
    path: /admin
  user:
    name: admin
    password: admin