server:
    port: 8080
    display-name: bs-dreamport-user
    context-path: /bs-dreamport-user

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.int(10000,19999)}
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/dreamport
        username: root
        password: 123456
        driverClassName: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

dreamport:
  druid:
    login:
      username: admin
      password: admin

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.dreamport.domain
  configuration:
    mapUnderscoreToCamelCase: true
    defaultStatementTimeout: 5000
    lazyLoadingEnabled: false

# Log 配置 级别大写 TRACE|DEBUG|INFO|WARN|ERROR
logging:
  level:
    #root: INFO
    com.dreamport: DEBUG
    com.ibatis: DEBUG
    java.sql: DEBUG

# actuator 安全性配置
security:
  basic:
    enabled:  true
    path: /admin
  user:
    name: admin
    password: admin